### ISSUE TITLE
No panel under Scene Properties

### ISSUE THREAD

**Issue by STEEL2** [negdo/SaveSelection#4]
Hi, thank's for your add-ons

I'm on Blender 3.4 and I've installed your add-on but under Scene properties I don"t see the panel with my older selection.

**Comment by negdo** [comment]
What version of the addon are you using? The pannel only exists in version 2.0.

**Comment by STEEL2** [comment]
I'm use version 0.9.0. I've buy this version on blender market and I don't see another version.

**Comment by negdo** [comment]
Try removing the addon and downloading it again. The files have been updated few weeks ago. If it still does not work, message me on the BlenderMarket.

**Comment by STEEL2** [comment]
Ok that the way to update the script. It's ok ! 

Thanks
