### ISSUE TITLE
Does not work in Blender 3.6.5

### ISSUE THREAD

**Issue by shibekin69** [negdo/SaveSelection#9]
Hi,

I'm trying your add-on out, and from a fresh install of Blender 3.6.5 LTS, it doesn't seem to work properly.

I can see the [Save Selection] and [Restore Selection] context menu items, but they don't do anything.
In the Scene Properties area, I only see a collapsible [Custom Properties] box.
After reinstalling and installing several times, I tried moving the saveCounter up by one, the [Save Selection] and [Restore Selection] seems to work, but it only knows the last selection made.

I made you a video so you can see what I saw:

https://github.com/negdo/SaveSelection/assets/12507139/a53ea8f7-af54-40a8-a794-6683da3090ec

Hope this helps!

**Comment by negdo** [comment]
Hi,

can you remove the addon, restart Blender and then open developer console. Do that by clicking Window > Toggle System Console.
![image](https://github.com/negdo/SaveSelection/assets/18052453/3f810210-14be-49f3-bf85-d74f1fd3d6d0)

THen try installing the addon and tell me, if you see any errors in the console.

**Comment by shibekin69** [comment]
Hi, this is what I see after uninstalling and reinstalling the addon:


![test](https://github.com/negdo/SaveSelection/assets/12507139/12eaa1ff-5e99-44b8-81fe-a7d5dbe97672)

**Comment by negdo** [comment]
May I know what version of the addon you are using and where did you download it?

**Comment by shibekin69** [comment]
I got it from here:

https://github.com/negdo/SaveSelection/releases/tag/0.9

**Comment by negdo** [comment]
Ah, sorry, I didn't make a newer release yet, but the code itself ha updeted a lot. Just try downloading the whole repository as zip and installing it.

**Comment by shibekin69** [comment]
Ok! Zipped up the main branch and tried it out. Seems to work as expected,at least with the basic cube!
